---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: api-dev
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  chartGitPath: api
  releaseName: api-dev
  values:
    image: gcr.io/rafine-co/rafine-api:dev-a1b138a3b090e8fbf2140f43a32a21baf79a46b7
    replicaCount: 1
    dbHost: gcloud-sqlproxy-dev-gcloud-sqlproxy
    ingress:
      enabled: false
