apiVersion: v1
kind: Service
metadata:
  name: {{ template "master.fullname" . }}
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ template "elasticsearch.chart" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    role: "master"
spec:
  ports:
  - name: transport
    port: 9300
    targetPort: transport
  selector:
    app: {{ template "elasticsearch.name" . }}
    release: {{ .Release.Name | quote }}
    role: "master"
