apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}-pg-proxy
  labels:
    app: {{ include "api.name" . }}
    chart: {{ include "api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "api.name" . }}
      release: {{ .Release.Name }}
spec:
  template:
    metadata:
      labels:
        app: {{ include "api.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances={{ .Values.dbConnectionName }}=tcp:5432",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          securityContext:
            runAsUser: 2  # non-root user
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
